name: 'Run Swift Tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_ENABLE_LOGGING : "true"
  AWS_LOG_LEVEL: "trace"

jobs:
  swift-tests:
    name: 'Swift Tests'
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          make test
      - name: Coverage
        run: |
          make coverage
      - name: Upload Code Coverage 
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/lcov.info